<?php

use Illuminate\Database\Seeder;

class SectoresEconomicosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$data = [
    	"Agricultura, ganadería, silvicultura y pesca",
    	"Agricultura, ganadería, caza y servicios relacionados con las mismas",
    	"Cultivos no perennes",
    	"Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas",
    	"Cultivo de arroz",
    	"Cultivo de hortalizas, raíces y tubérculos",
    	"Cultivo de caña de azúcar",
    	"Cultivo de tabaco",
    	"Cultivo de plantas para fibras textiles",
    	"Otros cultivos no perennes",
    	"Cultivos perennes",
    	"Cultivo de la vid",
    	"Cultivo de frutos tropicales y subtropicales",
    	"Cultivo de cítricos",
    	"Cultivo de frutos con hueso y pepitas",
    	"Cultivo de otros árboles y arbustos frutales y frutos secos",
    	"Cultivo de frutos oleaginosos",
    	"Cultivo de plantas para bebidas",
    	"Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas",
    	"Otros cultivos perennes",
    	"Propagación de plantas",
    	"Propagación de plantas",
    	"Producción ganadera",
    	"Explotación de ganado bovino para la producción de leche",
    	"Explotación de otro ganado bovino y búfalos",
    	"Explotación de caballos y otros equinos",
    	"Explotación de camellos y otros camélidos",
    	"Explotación de ganado ovino y caprino",
    	"Explotación de ganado porcino",
    	"Avicultura",
    	"Otras explotaciones de ganado",
    	"Producción agrícola combinada con la producción ganadera",
    	"Producción agrícola combinada con la producción ganadera",
    	"Actividades de apoyo a la agricultura, a la ganadería y de preparación posterior a la cosecha",
    	"Actividades de apoyo a la agricultura",
    	"Actividades de apoyo a la ganadería",
    	"Actividades de preparación posterior a la cosecha",
    	"Tratamiento de semillas para reproducción",
    	"Caza, captura de animales y servicios relacionados con las mismas",
    	"Caza, captura de animales y servicios relacionados con las mismas",
    	"Silvicultura y explotación forestal",
    	"Silvicultura y otras actividades forestales",
    	"Silvicultura y otras actividades forestales",
    	"Explotación de la madera",
    	"Explotación de la madera",
    	"Recolección de productos silvestres, excepto madera",
    	"Recolección de productos silvestres, excepto madera",
    	"Servicios de apoyo a la silvicultura",
    	"Servicios de apoyo a la silvicultura",
    	"Pesca y acuicultura",
    	"Pesca",
    	"Pesca marina",
    	"Pesca en agua dulce",
    	"Acuicultura",
    	"Acuicultura marina",
    	"Acuicultura en agua dulce",
    	"Industrias extractivas",
    	"Extracción de antracita, hulla y lignito",
    	"Extracción de antracita y hulla",
    	"Extracción de antracita y hulla",
    	"Extracción de lignito",
    	"Extracción de lignito",
    	"Extracción de crudo de petróleo y gas natural",
    	"Extracción de crudo de petróleo",
    	"Extracción de crudo de petróleo",
    	"Extracción de gas natural",
    	"Extracción de gas natural",
    	"Extracción de minerales metálicos",
    	"Extracción de minerales de hierro",
    	"Extracción de minerales de hierro",
    	"Extracción de minerales metálicos no férreos",
    	"Extracción de minerales de uranio y torio",
    	"Extracción de otros minerales metálicos no férreos",
    	"Otras industrias extractivas",
    	"Extracción de piedra, arena y arcilla",
    	"Extracción de piedra ornamental y para la construcción, piedra caliza, yeso, creta y pizarra",
    	"Extracción de gravas y arenas; extracción de arcilla y caolín",
    	"Industrias extractivas",
    	"Extracción de minerales para productos químicos y fertilizantes",
    	"Extracción de turba",
    	"Extracción de sal",
    	"Otras industrias extractivas",
    	"Actividades de apoyo a las industrias extractivas",
    	"Actividades de apoyo a la extracción de petróleo y gas natural",
    	"Actividades de apoyo a la extracción de petróleo y gas natural",
    	"Actividades de apoyo a otras industrias extractivas",
    	"Actividades de apoyo a otras industrias extractivas",
    	"Industria manufacturera",
    	"Industria de la alimentación",
    	"Procesado y conservación de carne y elaboración de productos cárnicos",
    	"Procesado y conservación de carne",
    	"Procesado y conservación de volatería",
    	"Elaboración de productos cárnicos y de volatería",
    	"Procesado y conservación de pescados, crustáceos y moluscos",
    	"Procesado de pescados, crustáceos y moluscos",
    	"Fabricación de conservas de pescado",
    	"Procesado y conservación de frutas y hortalizas",
    	"Procesado y conservación de patatas",
    	"Elaboración de zumos de frutas y hortalizas",
    	"Otro procesado y conservación de frutas y hortalizas",
    	"Fabricación de aceites y grasas vegetales y animales",
    	"Fabricación de margarina y grasas comestibles similares",
    	"Fabricación de aceite de oliva",
    	"Fabricación de otros aceites y grasas",
    	"Fabricación de productos lácteos",
    	"Elaboración de helados",
    	"Fabricación de quesos",
    	"Preparación de leche y otros productos lácteos",
    	"Fabricación de productos de molinería, almidones y productos amiláceos",
    	"Fabricación de productos de molinería",
    	"Fabricación de almidones y productos amiláceos",
    	"Fabricación de productos de panadería y pastas alimenticias",
    	"Fabricación de pan y de productos frescos de panadería y pastelería",
    	"Fabricación de galletas y productos de panadería y pastelería de larga duración",
    	"Fabricación de pastas alimenticias, cuscús y productos similares",
    	"Fabricación de otros productos alimenticios",
    	"Fabricación de azúcar",
    	"Fabricación de cacao, chocolate y productos de confitería",
    	"Elaboración de café, té e infusiones",
    	"Elaboración de especias, salsas y condimentos",
    	"Elaboración de platos y comidas preparados",
    	"Elaboración de preparados alimenticios homogeneizados y alimentos dietéticos",
    	"Elaboración de otros productos alimenticios",
    	"Fabricación de productos para la alimentación animal",
    	"Fabricación de productos para la alimentación de animales de granja",
    	"Fabricación de productos para la alimentación de animales de compañía",
    	"Fabricación de bebidas",
    	"Fabricación de bebidas",
    	"Destilación, rectificación y mezcla de bebidas alcohólicas",
    	"Elaboración de vinos",
    	"Elaboración de sidra y otras bebidas fermentadas a partir de frutas",
    	"Elaboración de otras bebidas no destiladas, procedentes de la fermentación",
    	"Fabricación de cerveza",
    	"Fabricación de malta",
    	"Fabricación de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas",
    	"Industria del tabaco",
    	"Industria del tabaco",
    	"Industria del tabaco",
    	"Industria textil",
    	"Preparación e hilado de fibras textiles",
    	"Preparación e hilado de fibras textiles",
    	"Fabricación de tejidos textiles",
    	"Fabricación de tejidos textiles",
    	"Acabado de textiles",
    	"Acabado de textiles",
    	"Fabricación de otros productos textiles",
    	"Fabricación de tejidos de punto",
    	"Fabricación de artículos confeccionados con textiles, excepto prendas de vestir",
    	"Fabricación de alfombras y moquetas",
    	"Fabricación de cuerdas, cordeles, bramantes y redes",
    	"Fabricación de telas no tejidas y artículos confeccionados con ellas, excepto prendas de vestir",
    	"Fabricación de otros productos textiles de uso técnico e industrial",
    	"Fabricación de otros productos textiles",
    	"Confección de prendas de vestir",
    	"Confección de prendas de vestir, excepto de peletería",
    	"Confección de prendas de vestir de cuero",
    	"Confección de ropa de trabajo",
    	"Confección de otras prendas de vestir exteriores",
    	"Confección de ropa interior",
    	"Confección de otras prendas de vestir y accesorios",
    	"Fabricación de artículos de peletería",
    	"Fabricación de artículos de peletería",
    	"Confección de prendas de vestir de punto",
    	"Confección de calcetería",
    	"Confección de otras prendas de vestir de punto",
    	"Industria del cuero y del calzado",
    	"Preparación, curtido y acabado del cuero; fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería; preparación y teñido de pieles",
    	"Preparación, curtido y acabado del cuero; preparación y teñido de pieles",
    	"Fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería",
    	"Fabricación de calzado",
    	"Fabricación de calzado",
    	"Industria de la madera y del corcho, excepto muebles; cestería y espartería",
    	"Aserrado y cepillado de la madera",
    	"Aserrado y cepillado de la madera",
    	"Fabricación de productos de madera, corcho, cestería y espartería",
    	"Fabricación de chapas y tableros de madera",
    	"Fabricación de suelos de madera ensamblados",
    	"Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción",
    	"Fabricación de envases y embalajes de madera",
    	"Fabricación de otros productos de madera; artículos de corcho, cestería y espartería",
    	"Industria del papel",
    	"Fabricación de pasta papelera, papel y cartón",
    	"Fabricación de pasta papelera",
    	"Fabricación de papel y cartón",
    	"Fabricación de artículos de papel y de cartón",
    	"Fabricación de papel y cartón ondulados; fabricación de envases y embalajes de papel y cartón",
    	"Fabricación de artículos de papel y cartón para uso doméstico, sanitario e higiénico",
    	"Fabricación de artículos de papelería",
    	"Fabricación de papeles pintados",
    	"Fabricación de otros artículos de papel y cartón",
    	"Artes gráficas y reproducción de soportes grabados",
    	"Artes gráficas y servicios relacionados con las mismas",
    	"Artes gráficas y servicios relacionados con las mismas",
    	"Otras actividades de impresión y artes gráficas",
    	"Servicios de preimpresión y preparación de soportes",
    	"Encuadernación y servicios relacionados con la misma",
    	"Reproducción de soportes grabados",
    	"Reproducción de soportes grabados",
    	"Coquerías y refino de petróleo",
    	"Coquerías",
    	"Coquerías",
    	"Refino de petróleo",
    	"Refino de petróleo",
    	"Industria química",
    	"Fabricación de productos químicos básicos, compuestos nitrogenados, fertilizantes, plásticos y caucho sintético en formas primarias",
    	"Fabricación de gases industriales",
    	"Fabricación de colorantes y pigmentos",
    	"Fabricación de otros productos básicos de química inorgánica",
    	"Fabricación de otros productos básicos de química orgánica",
    	"Fabricación de fertilizantes y compuestos nitrogenados",
    	"Fabricación de plásticos en formas primarias",
    	"Fabricación de caucho sintético en formas primarias",
    	"Fabricación de pesticidas y otros productos agroquímicos",
    	"Fabricación de pesticidas y otros productos agroquímicos",
    	"Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas",
    	"Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas",
    	"Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento; fabricación de perfumes y cosméticos",
    	"Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento",
    	"Fabricación de perfumes y cosméticos",
    	"Fabricación de otros productos químicos",
    	"Fabricación de explosivos",
    	"Fabricación de colas",
    	"Fabricación de aceites esenciales",
    	"Fabricación de otros productos químicos",
    	"Fabricación de fibras artificiales y sintéticas",
    	"Fabricación de fibras artificiales y sintéticas",
    	"Fabricación de productos farmacéuticos",
    	"Fabricación de productos farmacéuticos de base",
    	"Fabricación de productos farmacéuticos de base",
    	"Fabricación de especialidades farmacéuticas",
    	"Fabricación de especialidades farmacéuticas",
    	"Fabricación de productos de caucho y plásticos",
    	"Fabricación de productos de caucho",
    	"Fabricación de neumáticos y cámaras de caucho; reconstrucción y recauchutado de neumáticos",
    	"Fabricación de otros productos de caucho",
    	"Fabricación de productos de plástico",
    	"Fabricación de placas, hojas, tubos y perfiles de plástico",
    	"Fabricación de envases y embalajes de plástico",
    	"Fabricación de productos de plástico para la construcción",
    	"Fabricación de otros productos de plástico",
    	"Fabricación de otros productos minerales no metálicos",
    	"Fabricación de vidrio y productos de vidrio",
    	"Fabricación de vidrio plano",
    	"Manipulado y transformación de vidrio plano",
    	"Fabricación de vidrio hueco",
    	"Fabricación de fibra de vidrio",
    	"Fabricación y manipulado de otro vidrio, incluido el vidrio técnico",
    	"Fabricación de productos cerámicos refractarios",
    	"Fabricación de productos cerámicos refractarios",
    	"Fabricación de productos cerámicos para la construcción",
    	"Fabricación de azulejos y baldosas de cerámica",
    	"Fabricación de ladrillos, tejas y productos de tierras cocidas para la construcción",
    	"Fabricación de otros productos cerámicos",
    	"Fabricación de artículos cerámicos de uso doméstico y ornamental",
    	"Fabricación de aparatos sanitarios cerámicos",
    	"Fabricación de aisladores y piezas aislantes de material cerámico",
    	"Fabricación de otros productos cerámicos de uso técnico",
    	"Fabricación de otros productos cerámicos",
    	"Fabricación de cemento, cal y yeso",
    	"Fabricación de cemento",
    	"Fabricación de cal y yeso",
    	"Fabricación de elementos de hormigón, cemento y yeso",
    	"Fabricación de elementos de hormigón para la construcción",
    	"Fabricación de elementos de yeso para la construcción",
    	"Fabricación de hormigón fresco",
    	"Fabricación de mortero",
    	"Fabricación de fibrocemento",
    	"Fabricación de otros productos de hormigón, yeso y cemento",
    	"Corte, tallado y acabado de la piedra",
    	"Corte, tallado y acabado de la piedra",
    	"Fabricación de productos abrasivos y productos minerales no metálicos",
    	"Fabricación de productos abrasivos",
    	"Fabricación de otros productos minerales no metálicos",
    	"Metalurgia; fabricación de productos de hierro, acero y ferroaleaciones",
    	"Fabricación de productos básicos de hierro, acero y ferroaleaciones",
    	"Fabricación de productos básicos de hierro, acero y ferroaleaciones",
    	"Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero",
    	"Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero",
    	"Fabricación de otros productos de primera transformación del acero",
    	"Estirado en frío",
    	"Laminación en frío",
    	"Producción de perfiles en frío por conformación con plegado",
    	"Trefilado en frío",
    	"Producción de metales preciosos y de otros metales no férreos",
    	"Producción de metales preciosos",
    	"Producción de aluminio",
    	"Producción de plomo, zinc y estaño",
    	"Producción de cobre",
    	"Producción de otros metales no férreos",
    	"Procesamiento de combustibles nucleares",
    	"Fundición de metales",
    	"Fundición de hierro",
    	"Fundición de acero",
    	"Fundición de metales ligeros",
    	"Fundición de otros metales no férreos",
    	"Fabricación de productos metálicos, excepto maquinaria y equipo",
    	"Fabricación de elementos metálicos para la construcción",
    	"Fabricación de estructuras metálicas y sus componentes",
    	"Fabricación de carpintería metálica",
    	"Fabricación de cisternas, grandes depósitos y contenedores de metal",
    	"Fabricación de radiadores y calderas para calefacción central",
    	"Fabricación de otras cisternas, grandes depósitos y contenedores de metal",
    	"Fabricación de generadores de vapor, excepto calderas de calefacción central",
    	"Fabricación de generadores de vapor, excepto calderas de calefacción central",
    	"Fabricación de armas y municiones",
    	"Fabricación de armas y municiones",
    	"Forja, estampación y embutición de metales; metalurgia de polvos",
    	"Forja, estampación y embutición de metales; metalurgia de polvos",
    	"Tratamiento y revestimiento de metales; ingeniería mecánica por cuenta de terceros",
    	"Tratamiento y revestimiento de metales",
    	"Ingeniería mecánica por cuenta de terceros",
    	"Fabricación de artículos de cuchillería y cubertería, herramientas y ferretería",
    	"Fabricación de artículos de cuchillería y cubertería",
    	"Fabricación de cerraduras y herrajes",
    	"Fabricación de herramientas",
    	"Fabricación de otros productos metálicos",
    	"Fabricación de bidones y toneles de hierro o acero",
    	"Fabricación de envases y embalajes metálicos ligeros",
    	"Fabricación de productos de alambre, cadenas y muelles",
    	"Fabricación de pernos y productos de tornillería",
    	"Fabricación de otros productos metálicos",
    	"Fabricación de productos informáticos, electrónicos y ópticos",
    	"Fabricación de componentes electrónicos y circuitos impresos ensamblados",
    	"Fabricación de componentes electrónicos",
    	"Fabricación de circuitos impresos ensamblados",
    	"Fabricación de ordenadores y equipos periféricos",
    	"Fabricación de ordenadores y equipos periféricos",
    	"Fabricación de equipos de telecomunicaciones",
    	"Fabricación de equipos de telecomunicaciones",
    	"Fabricación de productos electrónicos de consumo",
    	"Fabricación de productos electrónicos de consumo",
    	"Fabricación de instrumentos y aparatos de medida, verificación y navegación; fabricación de relojes",
    	"Fabricación de instrumentos y aparatos de medida, verificación y navegación",
    	"Fabricación de relojes",
    	"Fabricación de equipos de radiación, electromédicos y electroterapéuticos",
    	"Fabricación de equipos de radiación, electromédicos y electroterapéuticos",
    	"Fabricación de instrumentos de óptica y equipo fotográfico",
    	"Fabricación de instrumentos de óptica y equipo fotográfico",
    	"Fabricación de soportes magnéticos y ópticos",
    	"Fabricación de soportes magnéticos y ópticos",
    	"Fabricación de material y equipo eléctrico",
    	"Fabricación de motores, generadores y transformadores eléctricos, y de aparatos de distribución y control eléctrico",
    	"Fabricación de motores, generadores y transformadores eléctricos",
    	"Fabricación de aparatos de distribución y control eléctrico",
    	"Fabricación de pilas y acumuladores eléctricos",
    	"Fabricación de pilas y acumuladores eléctricos",
    	"Fabricación de cables y dispositivos de cableado",
    	"Fabricación de cables de fibra óptica",
    	"Fabricación de otros hilos y cables electrónicos y eléctricos",
    	"Fabricación de dispositivos de cableado",
    	"Fabricación de lámparas y aparatos eléctricos de iluminación",
    	"Fabricación de lámparas y aparatos eléctricos de iluminación",
    	"Fabricación de aparatos domésticos",
    	"Fabricación de electrodomésticos",
    	"Fabricación de aparatos domésticos no eléctricos",
    	"Fabricación de otro material y equipo eléctrico",
    	"Fabricación de otro material y equipo eléctrico",
    	"Fabricación de maquinaria y equipo",
    	"Fabricación de maquinaria de uso general",
    	"Fabricación de motores y turbinas, excepto los destinados a aeronaves, vehículos automóviles y ciclomotores",
    	"Fabricación de equipos de transmisión hidráulica y neumática",
    	"Fabricación de otras bombas y compresores",
    	"Fabricación de otra grifería y válvulas",
    	"Fabricación de cojinetes, engranajes y órganos mecánicos de transmisión",
    	"Fabricación de otra maquinaria de uso general",
    	"Fabricación de hornos y quemadores",
    	"Fabricación de maquinaria de elevación y manipulación",
    	"Fabricación de máquinas y equipos de oficina, excepto equipos informáticos",
    	"Fabricación de herramientas eléctricas manuales",
    	"Fabricación de maquinaria de ventilación y refrigeración no doméstica",
    	"Fabricación de otra maquinaria de uso general",
    	"Fabricación de maquinaria agraria y forestal",
    	"Fabricación de maquinaria agraria y forestal",
    	"Fabricación de máquinas herramienta para trabajar el metal y otras máquinas herramienta",
    	"Fabricación de máquinas herramienta para trabajar el metal",
    	"Fabricación de otras máquinas herramienta",
    	"Fabricación de otra maquinaria para usos específicos",
    	"Fabricación de maquinaria para la industria metalúrgica",
    	"Fabricación de maquinaria para las industrias extractivas y de la construcción",
    	"Fabricación de maquinaria para la industria de la alimentación, bebidas y tabaco",
    	"Fabricación de maquinaria para las industrias textil, de la confección y del cuero",
    	"Fabricación de maquinaria para la industria del papel y del cartón",
    	"Fabricación de maquinaria para la industria del plástico y el caucho",
    	"Fabricación de otra maquinaria para usos específicos",
    	"Fabricación de vehículos de motor, remolques y semirremolques",
    	"Fabricación de vehículos de motor",
    	"Fabricación de vehículos de motor",
    	"Fabricación de carrocerías para vehículos de motor; fabricación de remolques y semirremolques",
    	"Fabricación de carrocerías para vehículos de motor; fabricación de remolques y semirremolques",
    	"Fabricación de componentes, piezas y accesorios para vehículos de motor",
    	"Fabricación de equipos eléctricos y electrónicos para vehículos de motor",
    	"Fabricación de otros componentes, piezas y accesorios para vehículos de motor",
    	"Fabricación de otro material de transporte",
    	"Construcción naval",
    	"Construcción de barcos y estructuras flotantes",
    	"Construcción de embarcaciones de recreo y deporte",
    	"Fabricación de locomotoras y material ferroviario",
    	"Fabricación de locomotoras y material ferroviario",
    	"Construcción aeronáutica y espacial y su maquinaria",
    	"Construcción aeronáutica y espacial y su maquinaria",
    	"Fabricación de vehículos militares de combate",
    	"Fabricación de vehículos militares de combate",
    	"Fabricación de otro material de transporte",
    	"Fabricación de motocicletas",
    	"Fabricación de bicicletas y de vehículos para personas con discapacidad",
    	"Fabricación de otro material de transporte",
    	"Fabricación de muebles",
    	"Fabricación de muebles",
    	"Fabricación de muebles de oficina y de establecimientos comerciales",
    	"Fabricación de muebles de cocina",
    	"Fabricación de colchones",
    	"Fabricación de otros muebles",
    	"Otras industrias manufactureras",
    	"Fabricación de artículos de joyería, bisutería y similares",
    	"Fabricación de monedas",
    	"Fabricación de artículos de joyería y artículos similares",
    	"Fabricación de artículos de bisutería y artículos similares",
    	"Fabricación de instrumentos musicales",
    	"Fabricación de instrumentos musicales",
    	"Fabricación de artículos de deporte",
    	"Fabricación de artículos de deporte",
    	"Fabricación de juegos y juguetes",
    	"Fabricación de juegos y juguetes",
    	"Fabricación de instrumentos y suministros médicos y odontológicos",
    	"Fabricación de instrumentos y suministros médicos y odontológicos",
    	"Industrias manufactureras",
    	"Fabricación de escobas, brochas y cepillos",
    	"Otras industrias manufactureras",
    	"Reparación e instalación de maquinaria y equipo",
    	"Reparación de productos metálicos, maquinaria y equipo",
    	"Reparación de productos metálicos",
    	"Reparación de maquinaria",
    	"Reparación de equipos electrónicos y ópticos",
    	"Reparación de equipos eléctricos",
    	"Reparación y mantenimiento naval",
    	"Reparación y mantenimiento aeronáutico y espacial",
    	"Reparación y mantenimiento de otro material de transporte",
    	"Reparación de otros equipos",
    	"Instalación de máquinas y equipos industriales",
    	"Instalación de máquinas y equipos industriales",
    	"Suministro de energía eléctrica, gas, vapor y aire acondicionado",
    	"Suministro de energía eléctrica, gas, vapor y aire acondicionado",
    	"Producción, transporte y distribución de energía eléctrica",
    	"Transporte de energía eléctrica",
    	"Distribución de energía eléctrica",
    	"Comercio de energía eléctrica",
    	"Producción de energía hidroeléctrica",
    	"Producción de energía eléctrica de origen térmico convencional",
    	"Producción de energía eléctrica de origen nuclear",
    	"Producción de energía eléctrica de origen eólico",
    	"Producción de energía eléctrica de otros tipos",
    	"Producción de gas; distribución por tubería de combustibles gaseosos",
    	"Producción de gas",
    	"Distribución por tubería de combustibles gaseosos",
    	"Comercio de gas por tubería",
    	"Suministro de vapor y aire acondicionado",
    	"Suministro de vapor y aire acondicionado",
    	"Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación",
    	"Captación, depuración y distribución de agua",
    	"Captación, depuración y distribución de agua",
    	"Captación, depuración y distribución de agua",
    	"Recogida y tratamiento de aguas residuales",
    	"Recogida y tratamiento de aguas residuales",
    	"Recogida y tratamiento de aguas residuales",
    	"Recogida, tratamiento y eliminación de residuos; valorización",
    	"Recogida de residuos",
    	"Recogida de residuos no peligrosos",
    	"Recogida de residuos peligrosos",
    	"Tratamiento y eliminación de residuos",
    	"Tratamiento y eliminación de residuos no peligrosos",
    	"Tratamiento y eliminación de residuos peligrosos",
    	"Valorización",
    	"Separación y clasificación de materiales",
    	"Valorización de materiales ya clasificados",
    	"Actividades de descontaminación y otros servicios de gestión de residuos",
    	"Actividades de descontaminación y otros servicios de gestión de residuos",
    	"Actividades de descontaminación y otros servicios de gestión de residuos",
    	"Construcción",
    	"Construcción de edificios",
    	"Promoción inmobiliaria",
    	"Promoción inmobiliaria",
    	"Construcción de edificios",
    	"Construcción de edificios residenciales",
    	"Construcción de edificios no residenciales",
    	"Ingeniería civil",
    	"Construcción de carreteras y vías férreas, puentes y túneles",
    	"Construcción de carreteras y autopistas",
    	"Construcción de vías férreas de superficie y subterráneas",
    	"Construcción de puentes y túneles",
    	"Construcción de redes",
    	"Construcción de redes para fluidos",
    	"Construcción de redes eléctricas y de telecomunicaciones",
    	"Construcción de otros proyectos de ingeniería civil",
    	"Obras hidráulicas",
    	"Construcción de otros proyectos de ingeniería civil",
    	"Actividades de construcción especializada",
    	"Demolición y preparación de terrenos",
    	"Demolición",
    	"Preparación de terrenos",
    	"Perforaciones y sondeos",
    	"Instalaciones eléctricas, de fontanería y otras instalaciones en obras de construcción",
    	"Instalaciones eléctricas",
    	"Fontanería, instalaciones de sistemas de calefacción y aire acondicionado",
    	"Otras instalaciones en obras de construcción",
    	"Acabado de edificios",
    	"Revocamiento",
    	"Instalación de carpintería",
    	"Revestimiento de suelos y paredes",
    	"Pintura y acristalamiento",
    	"Otro acabado de edificios",
    	"Otras actividades de construcción especializada",
    	"Construcción de cubiertas",
    	"Otras actividades de construcción especializada",
    	"Comercio al por mayor y al por menor; reparación de vehículos de motor y motocicletas",
    	"Venta y reparación de vehículos de motor y motocicletas",
    	"Venta de vehículos de motor",
    	"Venta de automóviles y vehículos de motor ligeros",
    	"Venta de otros vehículos de motor",
    	"Mantenimiento y reparación de vehículos de motor",
    	"Mantenimiento y reparación de vehículos de motor",
    	"Comercio de repuestos y accesorios de vehículos de motor",
    	"Comercio al por mayor de repuestos y accesorios de vehículos de motor",
    	"Comercio al por menor de repuestos y accesorios de vehículos de motor",
    	"Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios",
    	"Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios",
    	"Comercio al por mayor e intermediarios del comercio, excepto de vehículos de motor y motocicletas",
    	"Intermediarios del comercio",
    	"Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados",
    	"Intermediarios del comercio de combustibles, minerales, metales y productos químicos industriales",
    	"Intermediarios del comercio de la madera y materiales de construcción",
    	"Intermediarios del comercio de maquinaria, equipo industrial, embarcaciones y aeronaves",
    	"Intermediarios del comercio de muebles, artículos para el hogar y ferretería",
    	"Intermediarios del comercio de textiles, prendas de vestir, peletería, calzado y artículos de cuero",
    	"Intermediarios del comercio de productos alimenticios, bebidas y tabaco",
    	"Intermediarios del comercio especializados en la venta de otros productos específicos",
    	"Intermediarios del comercio de productos diversos",
    	"Comercio al por mayor de materias primas agrarias y de animales vivos",
    	"Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales",
    	"Comercio al por mayor de flores y plantas",
    	"Comercio al por mayor de animales vivos",
    	"Comercio al por mayor de cueros y pieles",
    	"Comercio al por mayor de productos alimenticios, bebidas y tabaco",
    	"Comercio al por mayor de frutas y hortalizas",
    	"Comercio al por mayor de carne y productos cárnicos",
    	"Comercio al por mayor de productos lácteos, huevos, aceites y grasas comestibles",
    	"Comercio al por mayor de bebidas",
    	"Comercio al por mayor de productos del tabaco",
    	"Comercio al por mayor de azúcar, chocolate y confitería",
    	"Comercio al por mayor de café, té, cacao y especias",
    	"Comercio al por mayor de pescados y mariscos y otros productos alimenticios",
    	"Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco",
    	"Comercio al por mayor de artículos de uso doméstico",
    	"Comercio al por mayor de textiles",
    	"Comercio al por mayor de prendas de vestir y calzado",
    	"Comercio al por mayor de aparatos electrodomésticos",
    	"Comercio al por mayor de porcelana, cristalería y artículos de limpieza",
    	"Comercio al por mayor de productos perfumería y cosmética",
    	"Comercio al por mayor de productos farmacéuticos",
    	"Comercio al por mayor de muebles, alfombras y aparatos de iluminación",
    	"Comercio al por mayor de artículos de relojería y joyería",
    	"Comercio al por mayor de otros artículos de uso doméstico",
    	"Comercio al por mayor de equipos para las tecnologías de la información y las comunicaciones",
    	"Comercio al por mayor de ordenadores, equipos periféricos y programas informáticos",
    	"Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes",
    	"Comercio al por mayor de otra maquinaria, equipos y suministros",
    	"Comercio al por mayor de maquinaria, equipos y suministros agrícolas",
    	"Comercio al por mayor de máquinas herramienta",
    	"Comercio al por mayor de maquinaria para la minería, la construcción y la ingeniería civil",
    	"Comercio al por mayor de maquinaria para la industria textil y de máquinas de coser y tricotar",
    	"Comercio al por mayor de muebles de oficina",
    	"Comercio al por mayor de otra maquinaria y equipo de oficina",
    	"Comercio al por mayor de otra maquinaria y equipo",
    	"Otro comercio al por mayor especializado",
    	"Comercio al por mayor de combustibles sólidos, líquidos y gaseosos, y productos similares",
    	"Comercio al por mayor de metales y minerales metálicos",
    	"Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios",
    	"Comercio al por mayor de ferretería, fontanería y calefacción",
    	"Comercio al por mayor de productos químicos",
    	"Comercio al por mayor de otros productos semielaborados",
    	"Comercio al por mayor de chatarra y productos de desecho",
    	"Comercio al por mayor no especializado",
    	"Comercio al por mayor no especializado",
    	"Comercio al por menor, excepto de vehículos de motor y motocicletas",
    	"Comercio al por menor en establecimientos no especializados",
    	"Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco",
    	"Otro comercio al por menor en establecimientos no especializados",
    	"Comercio al por menor de productos alimenticios, bebidas y tabaco en establecimientos especializados",
    	"Comercio al por menor de frutas y hortalizas en establecimientos especializados",
    	"Comercio al por menor de carne y productos cárnicos en establecimientos especializados",
    	"Comercio al por menor de pescados y mariscos en establecimientos especializados",
    	"Comercio al por menor de pan y productos de panadería, confitería y pastelería en establecimientos especializados",
    	"Comercio al por menor de bebidas en establecimientos especializados",
    	"Comercio al por menor de productos de tabaco en establecimientos especializados",
    	"Otro comercio al por menor de productos alimenticios en establecimientos especializados",
    	"Comercio al por menor de combustible para la automoción en establecimientos especializados",
    	"Comercio al por menor de combustible para la automoción en establecimientos especializados",
    	"Comercio al por menor de equipos para las tecnologías de la información y las comunicaciones en establecimientos especializados",
    	"Comercio al por menor de ordenadores, equipos periféricos y programas informáticos en establecimientos especializados",
    	"Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados",
    	"Comercio al por menor de equipos de audio y vídeo en establecimientos especializados",
    	"Comercio al por menor de otros artículos de uso doméstico en establecimientos especializados",
    	"Comercio al por menor de textiles en establecimientos especializados",
    	"Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados",
    	"Comercio al por menor de alfombras, moquetas y revestimientos de paredes y suelos en establecimientos especializados",
    	"Comercio al por menor de aparatos electrodomésticos en establecimientos especializados",
    	"Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados",
    	"Comercio al por menor de artículos culturales y recreativos en establecimientos especializados",
    	"Comercio al por menor de libros en establecimientos especializados",
    	"Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados",
    	"Comercio al por menor de grabaciones de música y vídeo en establecimientos especializados",
    	"Comercio al por menor de artículos deportivos en establecimientos especializados",
    	"Comercio al por menor de juegos y juguetes en establecimientos especializados",
    	"Comercio al por menor de otros artículos en establecimientos especializados",
    	"Comercio al por menor de prendas de vestir en establecimientos especializados",
    	"Comercio al por menor de calzado y artículos de cuero en establecimientos especializados",
    	"Comercio al por menor de productos farmacéuticos en establecimientos especializados",
    	"Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados",
    	"Comercio al por menor de productos cosméticos e higiénicos en establecimientos especializados",
    	"Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados",
    	"Comercio al por menor de artículos de relojería y joyería en establecimientos especializados",
    	"Otro comercio al por menor de artículos nuevos en establecimientos especializados",
    	"Comercio al por menor de artículos de segunda mano en establecimientos",
    	"Comercio al por menor en puestos de venta y en mercadillos",
    	"Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y en mercadillos",
    	"Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercadillos",
    	"Comercio al por menor de otros productos en puestos de venta y en mercadillos",
    	"Comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercadillos",
    	"Comercio al por menor por correspondencia o Internet",
    	"Otro comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercadillos",
    	"Transporte y almacenamiento",
    	"Transporte terrestre y por tubería",
    	"Transporte interurbano de pasajeros por ferrocarril",
    	"Transporte interurbano de pasajeros por ferrocarril",
    	"Transporte de mercancías por ferrocarril",
    	"Transporte de mercancías por ferrocarril",
    	"Otro transporte terrestre de pasajeros",
    	"Transporte terrestre urbano y suburbano de pasajeros",
    	"Transporte por taxi",
    	"Otros tipos de transporte terrestre de pasajeros",
    	"Transporte de mercancías por carretera y servicios de mudanza",
    	"Transporte de mercancías por carretera",
    	"Servicios de mudanza",
    	"Transporte por tubería",
    	"Transporte por tubería",
    	"Transporte marítimo y por vías navegables interiores",
    	"Transporte marítimo de pasajeros",
    	"Transporte marítimo de pasajeros",
    	"Transporte marítimo de mercancías",
    	"Transporte marítimo de mercancías",
    	"Transporte de pasajeros por vías navegables interiores",
    	"Transporte de pasajeros por vías navegables interiores",
    	"Transporte de mercancías por vías navegables interiores",
    	"Transporte de mercancías por vías navegables interiores",
    	"Transporte aéreo",
    	"Transporte aéreo de pasajeros",
    	"Transporte aéreo de pasajeros",
    	"Transporte aéreo de mercancías y transporte espacial",
    	"Transporte aéreo de mercancías",
    	"Transporte espacial",
    	"Almacenamiento y actividades anexas al transporte",
    	"Depósito y almacenamiento",
    	"Depósito y almacenamiento",
    	"Actividades anexas al transporte",
    	"Actividades anexas al transporte terrestre",
    	"Actividades anexas al transporte marítimo y por vías navegables interiores",
    	"Actividades anexas al transporte aéreo",
    	"Manipulación de mercancías",
    	"Otras actividades anexas al transporte",
    	"Actividades postales y de correos",
    	"Actividades postales sometidas a la obligación del servicio universal",
    	"Actividades postales sometidas a la obligación del servicio universal",
    	"Otras actividades postales y de correos",
    	"Otras actividades postales y de correos",
    	"Hostelería",
    	"Servicios de alojamiento",
    	"Hoteles y alojamientos similares",
    	"Hoteles y alojamientos similares",
    	"Alojamientos turísticos y otros alojamientos de corta estancia",
    	"Alojamientos turísticos y otros alojamientos de corta estancia",
    	"Campings y aparcamientos para caravanas",
    	"Campings y aparcamientos para caravanas",
    	"Otros alojamientos",
    	"Otros alojamientos",
    	"Servicios de comidas y bebidas",
    	"Restaurantes y puestos de comidas",
    	"Restaurantes y puestos de comidas",
    	"Provisión de comidas preparadas para eventos y otros servicios de comidas",
    	"Provisión de comidas preparadas para eventos",
    	"Otros servicios de comidas",
    	"Establecimientos de bebidas",
    	"Establecimientos de bebidas",
    	"Información y comunicaciones",
    	"Edición",
    	"Edición de libros, periódicos y otras actividades editoriales",
    	"Edición de libros",
    	"Edición de directorios y guías de direcciones postales",
    	"Edición de periódicos",
    	"Edición de revistas",
    	"Otras actividades editoriales",
    	"Edición de programas informáticos",
    	"Edición de videojuegos",
    	"Edición de otros programas informáticos",
    	"Actividades cinematográficas, de vídeo y de programas de televisión, grabación de sonido y edición musical",
    	"Actividades cinematográficas, de vídeo y de programas de televisión",
    	"Actividades de postproducción cinematográfica, de vídeo y de programas de televisión",
    	"Actividades de exhibición cinematográfica",
    	"Actividades de producción cinematográfica y de vídeo",
    	"Actividades de producciones de programas de televisión",
    	"Actividades de distribución cinematográfica y de vídeo",
    	"Actividades de distribución de programas de televisión",
    	"Actividades de grabación de sonido y edición musical",
    	"Actividades de grabación de sonido y edición musical",
    	"Actividades de programación y emisión de radio y televisión",
    	"Actividades de radiodifusión",
    	"Actividades de radiodifusión",
    	"Actividades de programación y emisión de televisión",
    	"Actividades de programación y emisión de televisión",
    	"Telecomunicaciones",
    	"Telecomunicaciones por cable",
    	"Telecomunicaciones por cable",
    	"Telecomunicaciones inalámbricas",
    	"Telecomunicaciones inalámbricas",
    	"Telecomunicaciones por satélite",
    	"Telecomunicaciones por satélite",
    	"Otras actividades de telecomunicaciones",
    	"Otras actividades de telecomunicaciones",
    	"Programación, consultoría y otras actividades relacionadas con la informática",
    	"Programación, consultoría y otras actividades relacionadas con la informática",
    	"Actividades de programación informática",
    	"Actividades de consultoría informática",
    	"Gestión de recursos informáticos",
    	"Otros servicios relacionados con las tecnologías de la información y la informática",
    	"Servicios de información",
    	"Proceso de datos, hosting y actividades relacionadas; portales web",
    	"Proceso de datos, hosting y actividades relacionadas",
    	"Portales web",
    	"Otros servicios de información",
    	"Actividades de las agencias de noticias",
    	"Otros servicios de información",
    	"Actividades financieras y de seguros",
    	"Servicios financieros, excepto seguros y fondos de pensiones",
    	"Intermediación monetaria",
    	"Banco central",
    	"Otra intermediación monetaria",
    	"Actividades de las sociedades holding",
    	"Actividades de las sociedades holding",
    	"Inversión colectiva, fondos y entidades financieras similares",
    	"Inversión colectiva, fondos y entidades financieras similares",
    	"Otros servicios financieros, excepto seguros y fondos de pensiones",
    	"Arrendamiento financiero",
    	"Otras actividades crediticias",
    	"Otros servicios financieros, excepto seguros y fondos de pensiones",
    	"Seguros, reaseguros y fondos de pensiones, excepto Seguridad Social obligatoria",
    	"Seguros",
    	"Seguros de vida",
    	"Seguros distintos de los seguros de vida",
    	"Reaseguros",
    	"Reaseguros",
    	"Fondos de pensiones",
    	"Fondos de pensiones",
    	"Actividades auxiliares a los servicios financieros y a los seguros",
    	"Actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones",
    	"Administración de mercados financieros",
    	"Actividades de intermediación en operaciones con valores y otros activos",
    	"Otras actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones",
    	"Actividades auxiliares a seguros y fondos de pensiones",
    	"Evaluación de riesgos y daños",
    	"Actividades de agentes y corredores de seguros",
    	"Otras actividades auxiliares a seguros y fondos de pensiones",
    	"Actividades de gestión de fondos",
    	"Actividades de gestión de fondos",
    	"Actividades inmobiliarias",
    	"Actividades inmobiliarias",
    	"Compraventa de bienes inmobiliarios por cuenta propia",
    	"Compraventa de bienes inmobiliarios por cuenta propia",
    	"Alquiler de bienes inmobiliarios por cuenta propia",
    	"Alquiler de bienes inmobiliarios por cuenta propia",
    	"Actividades inmobiliarias por cuenta de terceros",
    	"Agentes de la propiedad inmobiliaria",
    	"Gestión y administración de la propiedad inmobiliaria",
    	"Actividades profesionales, científicas y técnicas",
    	"Actividades jurídicas y de contabilidad",
    	"Actividades jurídicas",
    	"Actividades jurídicas",
    	"Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal",
    	"Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal",
    	"Actividades de las sedes centrales; actividades de consultoría de gestión empresarial",
    	"Actividades de las sedes centrales",
    	"Actividades de las sedes centrales",
    	"Actividades de consultoría de gestión empresarial",
    	"Relaciones públicas y comunicación",
    	"Otras actividades de consultoría de gestión empresarial",
    	"Servicios técnicos de arquitectura e ingeniería; ensayos y análisis técnicos",
    	"Servicios técnicos de arquitectura e ingeniería y otras actividades relacionadas con el asesoramiento técnico",
    	"Servicios técnicos de arquitectura",
    	"Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico",
    	"Ensayos y análisis técnicos",
    	"Ensayos y análisis técnicos",
    	"Investigación y desarrollo",
    	"Investigación y desarrollo experimental en ciencias naturales y técnicas",
    	"Investigación y desarrollo experimental en biotecnología",
    	"Otra investigación y desarrollo experimental en ciencias naturales y técnicas",
    	"Investigación y desarrollo experimental en ciencias sociales y humanidades",
    	"Publicidad y estudios de mercado",
    	"Publicidad",
    	"Agencias de publicidad",
    	"Servicios de representación de medios de comunicación",
    	"Estudio de mercado y realización de encuestas de opinión pública",
    	"Estudio de mercado y realización de encuestas de opinión pública",
    	"Otras actividades profesionales, científicas y técnicas",
    	"Actividades de diseño especializado",
    	"Actividades de diseño especializado",
    	"Actividades de fotografía",
    	"Actividades de traducción e interpretación",
    	"Actividades de traducción e interpretación",
    	"Otras actividades profesionales, científicas y técnicas",
    	"Otras actividades profesionales, científicas y técnicas",
    	"Actividades veterinarias",
    	"Actividades administrativas y servicios auxliares",
    	"Actividades de alquiler",
    	"Alquiler de vehículos de motor",
    	"Alquiler de automóviles y vehículos de motor ligeros",
    	"Alquiler de camiones",
    	"Alquiler de efectos personales y artículos de uso doméstico",
    	"Alquiler de artículos de ocio y deportivos",
    	"Alquiler de cintas de vídeo y discos",
    	"Alquiler de otros efectos personales y artículos de uso doméstico",
    	"Alquiler de otra maquinaria, equipos y bienes tangibles",
    	"Alquiler de maquinaria y equipo de uso agrícola",
    	"Alquiler de maquinaria y equipo para la construcción e ingeniería civil",
    	"Alquiler de maquinaria y equipo de oficina, incluidos ordenadores",
    	"Alquiler de medios de navegación",
    	"Alquiler de medios de transporte aéreo",
    	"Alquiler de otra maquinaria, equipos y bienes tangibles",
    	"Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor",
    	"Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor",
    	"Actividades relacionadas con el empleo",
    	"Actividades de las agencias de colocación",
    	"Actividades de las agencias de colocación",
    	"Actividades de las empresas de trabajo temporal",
    	"Otra provisión de recursos humanos",
    	"Otra provisión de recursos humanos",
    	"Actividades de agencias de viajes, operadores turísticos, servicios de reservas y actividades relacionadas con los mismos",
    	"Actividades de agencias de viajes y operadores turísticos",
    	"Actividades de las agencias de viajes",
    	"Actividades de los operadores turísticos",
    	"Otros servicios de reservas y actividades relacionadas con los mismos",
    	"Otros servicios de reservas y actividades relacionadas con los mismos",
    	"Actividades de seguridad e investigación",
    	"Actividades de seguridad privada",
    	"Actividades de seguridad privada",
    	"Servicios de sistemas de seguridad",
    	"Servicios de sistemas de seguridad",
    	"Actividades de investigación",
    	"Actividades de investigación",
    	"Servicios a edificios y actividades de jardinería",
    	"Servicios integrales a edificios e instalaciones",
    	"Servicios integrales a edificios e instalaciones",
    	"Actividades de limpieza",
    	"Limpieza general de edificios",
    	"Otras actividades de limpieza industrial y de edificios",
    	"Otras actividades de limpieza",
    	"Actividades de jardinería",
    	"Actividades de jardinería",
    	"Actividades administrativas de oficina y otras actividades auxiliares a las empresas",
    	"Actividades administrativas y auxiliares de oficina",
    	"Servicios administrativos combinados",
    	"Actividades de fotocopiado, preparación de documentos y otras actividades especializadas de oficina",
    	"Actividades de los centros de llamadas",
    	"Organización de convenciones y ferias de muestras",
    	"Organización de convenciones y ferias de muestras",
    	"Actividades de apoyo a las empresas",
    	"Actividades de las agencias de cobros y de información comercial",
    	"Actividades de envasado y empaquetado",
    	"Otras actividades de apoyo a las empresas",
    	"Administración Pública y defensa; Seguridad Social obligatoria",
    	"Administración Pública y defensa; Seguridad Social obligatoria",
    	"Administración Pública y de la política económica y social",
    	"Actividades generales de la Administración Pública",
    	"Regulación de las actividades sanitarias, educativas y culturales y otros servicios sociales, excepto Seguridad Social",
    	"Regulación de la actividad económica y contribución a su mayor eficiencia",
    	"Prestación de servicios a la comunidad en general",
    	"Asuntos exteriores",
    	"Defensa",
    	"Justicia",
    	"Orden público y seguridad",
    	"Protección civil",
    	"Seguridad Social obligatoria",
    	"Seguridad Social obligatoria",
    	"Educación",
       	"Educación preprimaria",
    	"Educación preprimaria",
    	"Educación primaria",
    	"Educación secundaria",
    	"Educación secundaria general",
    	"Educación secundaria técnica y profesional",
    	"Educación postsecundaria",
    	"Educación postsecundaria no terciaria",
    	"Educación universitaria",
    	"Educación terciaria no universitaria",
    	"Otra educación",
    	"Educación deportiva y recreativa",
    	"Educación cultural",
    	"Actividades de las escuelas de conducción y pilotaje",
    	"Otra educación",
    	"Actividades auxiliares a la educación",
    	"Actividades auxiliares a la educación",
    	"Actividades sanitarias y de servicios sociales",
    	"Actividades sanitarias",
    	"Actividades hospitalarias",
    	"Actividades hospitalarias",
    	"Actividades médicas y odontológicas",
    	"Actividades de medicina general",
    	"Actividades de medicina especializada",
    	"Actividades odontológicas",
    	"Otras actividades sanitarias",
    	"Otras actividades sanitarias",
    	"Asistencia en establecimientos residenciales",
    	"Asistencia en establecimientos residenciales con cuidados sanitarios",
    	"Asistencia en establecimientos residenciales con cuidados sanitarios",
    	"Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia",
    	"Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia",
    	"Asistencia en establecimientos residenciales para personas mayores y con discapacidad física",
    	"Asistencia en establecimientos residenciales para personas mayores",
    	"Asistencia en establecimientos residenciales para personas con discapacidad física",
    	"Otras actividades de asistencia en establecimientos residenciales",
    	"Otras actividades de asistencia en establecimientos residenciales",
    	"Actividades de servicios sociales sin alojamiento",
    	"Actividades de servicios sociales sin alojamiento para personas mayores y con discapacidad",
    	"Actividades de servicios sociales sin alojamiento para personas mayores",
    	"Actividades de servicios sociales sin alojamiento para personas con discapacidad",
    	"Otros actividades de servicios sociales sin alojamiento",
    	"Actividades de cuidado diurno de niños",
    	"Otros actividades de servicios sociales sin alojamiento",
    	"Actividades artísticas, recreativas y de entretenimiento",
    	"Actividades de creación, artísticas y espectáculos",
    	"Actividades de creación, artísticas y espectáculos",
    	"Artes escénicas",
    	"Actividades auxiliares a las artes escénicas",
    	"Creación artística y literaria",
    	"Gestión de salas de espectáculos",
    	"Actividades de bibliotecas, archivos, museos y otras actividades culturales",
    	"Actividades de bibliotecas, archivos, museos y otras actividades culturales",
    	"Actividades de museos",
    	"Gestión de lugares y edificios históricos",
    	"Actividades de los jardines botánicos, parques zoológicos y reservas naturales",
    	"Actividades de bibliotecas",
    	"Actividades de archivos",
    	"Actividades de juegos de azar y apuestas",
    	"Actividades de juegos de azar y apuestas",
    	"Actividades de juegos de azar y apuestas",
    	"Actividades deportivas, recreativas y de entretenimiento",
    	"Actividades deportivas",
    	"Gestión de instalaciones deportivas",
    	"Actividades de los clubes deportivos",
    	"Actividades de los gimnasios",
    	"Otras actividades deportivas",
    	"Actividades recreativas y de entretenimiento",
    	"Actividades de los parques de atracciones y los parques temáticos",
    	"Otras actividades recreativas y de entretenimiento",
    	"Otros servicios",
    	"Actividades asociativas",
    	"Actividades de organizaciones empresariales, profesionales y patronales",
    	"Actividades de organizaciones empresariales y patronales",
    	"Actividades de organizaciones profesionales",
    	"Actividades sindicales",
    	"Actividades sindicales",
    	"Otras actividades asociativas",
    	"Actividades de organizaciones religiosas",
    	"Actividades de organizaciones políticas",
    	"Otras actividades asociativas",
    	"Reparación de ordenadores, efectos personales y artículos de uso doméstico",
    	"Reparación de ordenadores y equipos de comunicación",
    	"Reparación de ordenadores y equipos periféricos",
    	"Reparación de equipos de comunicación",
    	"Reparación de efectos personales y artículos de uso doméstico",
    	"Reparación de aparatos electrónicos de audio y vídeo de uso doméstico",
    	"Reparación de aparatos electrodomésticos y de equipos para el hogar y el jardín",
    	"Reparación de calzado y artículos de cuero",
    	"Reparación de muebles y artículos de menaje",
    	"Reparación de relojes y joyería",
    	"Reparación de otros efectos personales y artículos de uso doméstico",
    	"Otros servicios personales",
    	"Otros servicios personales",
    	"Lavado y limpieza de prendas textiles y de piel",
    	"Peluquería y otros tratamientos de belleza",
    	"Pompas fúnebres y actividades relacionadas",
    	"Actividades de mantenimiento físico",
    	"Otras servicios personales",
    	"Actividades de los hogares como empleadores de personal doméstico; actividades de los hogares como productores de bienes y servicios para uso propio",
    	"Actividades de los hogares como empleadores de personal doméstico",
    	"Actividades de los hogares como empleadores de personal doméstico",
    	"Actividades de los hogares como empleadores de personal doméstico",
    	"Actividades de los hogares como productores de bienes y servicios para uso propio",
    	"Actividades de los hogares como productores de bienes para uso propio",
    	"Actividades de los hogares como productores de bienes para uso propio",
    	"Actividades de los hogares como productores de servicios para uso propio",
    	"Actividades de los hogares como productores de servicios para uso propio",
    	"Actividades de organizaciones y organismos extraterritoriales",
    	"Actividades de organizaciones y organismos extraterritoriales",
    	"Actividades de organizaciones y organismos extraterritoriales",
    	"Actividades de organizaciones y organismos extraterritoriales"
    	];

    for ($i=0; $i < count($data) ; $i++) { 
    	 DB::table('sectores_economicos')->insert([
            'nombre' => $data[$i]
        ]);
    }

    	 

    }
}
